import type { Metadata } from "next";
import "./globals.css";
import CustomThemeProvider from "@/components/theme-provider"; // ✅ 수정된 ThemeProvider 사용
import Providers from "@/components/providers"; // ✅ WalletProvider를 분리하여 import

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CustomThemeProvider>{children}</CustomThemeProvider>
        </Providers>
      </body>
    </html>
  );
}